remove kdeconnect cask
It breaks homebrew upgrades with the following message.
And the cask itself is now non-installable.

Error: Calling cask `url do` blocks is deprecated! There is no replacement.
Please report this issue:
  https://docs.brew.sh/Troubleshooting

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>